# Generated by Django 3.0.5 on 2020-05-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(max_length=50, null=True)),
                ('pendidikan', models.CharField(max_length=150, null=True)),
                ('bio', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
